config/routes.rb
NSSToDoList::Application.routes.draw do
  root to: "lists#index"

  resources :lists, only: [:index, :create, :destroy]
  resources :tasks, only: [:create, :destroy]
  
  resources :lists do
    resources :tasks
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  attr_accessible :title, :id
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_one :list
  attr_accessible :name, :list_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
    @task = Task.new
  end

  def create
    @list = List.create(params[:list])
    flash[:notice] = "Your list has been added."
    redirect_to :root
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    flash[:notice] = "Your list has been deleted."
    redirect_to :root
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.create(params[:task])
    flash[:notice] = "Your task has been added."
    redirect_to :root
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Your task has been deleted."
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NSSToDoList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
  <%= message %>
<% end %>

<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1>To-Do Lists</h1>

<% @lists.each do |list| %>
  <h2><%= list.title %> <%= link_to "Delete", list, :confirm => "Are you sure?", :method => :delete %></h2>
  <ul>
    <% list.tasks.each do |task| %>
      <li><%= task.name %> <%= link_to "Delete", task, :confirm => "Are you sure?", :method => :delete %></li>
    <% end %>
  </ul>
  <%= form_for [list, @task] do |f| %>
    <%= f.label :name, "Enter Task:" %>
    <%= f.text_field :name %>
    <%= f.submit "Submit" %>
  <% end %>

<% end %>
<br>
<hr>
<h1>Add List</h1>
<%= form_for @list do |f| %>
  <%= f.label :title, "Enter List Name:" %>
  <%= f.text_field :title %>
  <%= f.submit "Submit" %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= form_for @list do |f| %>
  <%= f.label :title, "Enter List:" %>
  <%= f.text_field :title %>
  <%= f.submit "Submit List" %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= task.name %></li>
  <% end %>
</ul>

<%= link_to "New Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for @task do |f| %>
  <%= f.label :name, "Enter Task:" %>
  <%= f.text_field :name %>
  <%= f.submit "Submit Task" %>
<% end %>